# Generated by Django 3.1.7 on 2021-03-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='body',
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default='DEFAULT VALUE', max_length=700),
        ),
    ]
